### ISSUE TITLE
Volatile bug?

### ISSUE THREAD

**Issue by akemrir** [Shougo/ddc.vim#49] opened 2021-09-13 16:59 UTC
I have problem with volatile option.

I've created very simple sample extension, and I make it volatile.
When I run vim on one terminal with minimal setup, and sample code on the other.
Then I change available options, they are not reloaded.

Software:
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 28 2021 06:58:52)
Zadane łaty: 1-2891
Skompilowany przez Arch Linux

5.13.13-1-MANJARO updated with latest packages available in repository

Plugins:
ddc-around 82df6d0
ddc.vim b78349c
ddc-matcher_head 6413635
ddc-sorter_rank 5af81b0
denops.vim ee7fab4

Command:
vim -u ~/.vimrc-ddc-sample

Files:
ddc-sample/denops/ddc-sources/sample.ts
```
import {
  BaseSource,
  Candidate,
  Context
} from "https://deno.land/x/ddc_vim@v0.3.0/types.ts#^";
import { readLines, writeAll } from "https://deno.land/std@0.106.0/io/mod.ts#^";

export class Source extends BaseSource {
  _proc: Deno.Process | undefined = undefined;

  constructor() {
    super();
  }

  async gatherCandidates(args: { context: Context }): Promise<Candidate[]> {
    return [
      { word: "sample1" },
      { word: "sample2" },
      { word: "xample1V" },
      { word: "xample1Vx" },
      { word: "xample9V" },
      { word: "xample9Vx" },
      { word: "xample2V" },
      { word: "wir" },
      { word: "wira" }
    ];
  }
}
```

.vimrc
```
" # VIMRC deno sample #

if &compatible
  set nocompatible
endif

filetype plugin indent on
syntax enable
let mapleader = "\<Space>"
if &shell =~# 'fish$'
  set shell=sh
endif

set path=**,./
set tags+=.git/tags

call plug#begin('~/.vim/plugged')
Plug 'Shougo/ddc.vim'
Plug 'vim-denops/denops.vim'
Plug 'Shougo/ddc-around'
Plug 'Shougo/ddc-matcher_head'
Plug 'Shougo/ddc-sorter_rank'
Plug '~/.vim/plugins/ddc-sample'
call plug#end()

" Use around source.
call ddc#custom#patch_global('sources', ['around', 'sample'])

call ddc#custom#patch_global('sourceOptions', {
      \ '_': {
      \   'matchers': ['matcher_head'],
      \   'sorters': ['sorter_rank']},
      \   'minAutoCompleteLength': 1
      \ })

call ddc#custom#patch_global('sourceOptions', {
      \ 'sample': {
      \   'mark': 'S',
      \   'isVolatile': v:true,
      \   'minAutoCompleteLength': 1
      \ }})

" Change source options
call ddc#custom#patch_global('sourceOptions', {
      \ 'around': {'mark': 'A'},
      \ })
call ddc#custom#patch_global('sourceParams', {
      \ 'around': {'maxSize': 500},
      \ })

" <TAB>: completion.
inoremap <silent><expr> <TAB>
\ pumvisible() ? '<C-n>' :
\ (col('.') <= 1 <Bar><Bar> getline('.')[col('.') - 2] =~# '\s') ?
\ '<TAB>' : ddc#manual_complete()

" <S-TAB>: completion back.
inoremap <expr><S-TAB>  pumvisible() ? '<C-p>' : '<C-h>'

" Use ddc.
call ddc#enable()
```

**Comment by Shougo** [comment] 2021-09-14 00:42
> When I run vim on one terminal with minimal setup, and sample code on the other.
> Then I change available options, they are not reloaded.

It is very fuzzy description.
Please explain it more clearly.  I cannot reproduce the problem.

**Comment by Shougo** [comment] 2021-09-14 00:43
For example, it is perfect description.

https://github.com/Shougo/ddc.vim/issues/45

Please compare it with yours.

**Comment by akemrir** [comment] 2021-09-15 05:54
Sorry for fuzzy description.
Let's say: I was changing the source of addon in separate program and results does not change.

But maybe my testing approach is not valid.
Does deno buffer source code of addon in some kind of cache?

**Comment by Shougo** [comment] 2021-09-15 07:31
The buffer source is already cached internally.
So the result may not be exact.

**Comment by Shougo** [comment] 2021-09-15 07:32
isVolatile means disable ddc.vim cache.
It doesn't affect with the source level cache.

**Comment by akemrir** [comment] 2021-09-15 18:42
So to achieve fresh results I need to make approach similar to code in ddc-nextword.
Run external app from inside of addon.

**Comment by Shougo** [comment] 2021-09-15 23:01
Your configuration is wrong.  It seems `sourceParams` instead of `sourceOptions`.

You need to know what you do.

It should be:

```vim
autocmd FileType * call ddc#custom#patch_buffer('sourceParams', {
      \   'tags': map(tagfiles(), 'fnamemodify(v:val, ":p")'),
      \   'dict': map(split(&l:dictionary, ','), 'fnamemodify(v:val, ":p")')
      \ })
```

**Comment by Shougo** [comment] 2021-09-15 23:06
Please describe what your source want to do.  We don't have ESP skills.

> So to achieve fresh results I need to make approach similar to code in ddc-nextword.

I think you should cache files in `onEvent()`.

**Comment by akemrir** [comment] 2021-09-16 13:13
The plan is this:
1. user starts to type
2. vim gathers tags and dictionaries files list
3. vim sends them to deno source
4. deno runs ripgrep on those files and filters output with user input
5. source returns found words list

There are two factors affecting results:
- user input
- file list

**Comment by Shougo** [comment] 2021-09-17 02:17
> vim gathers tags and dictionaries files list

It should be implemented by `onEvent()`.
`:help ddc-source-attribute-onEvent`

You should read the implementation.
It is not ddc problem.  Closing.

**Closed by Shougo** 2021-09-17 02:17 UTC
Labels: cannot reproduce

**Comment by akemrir** [comment] 2021-09-17 14:34
You are absolutely right. Thanks for help.
